[package]
name = "rust-kv-store"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.32", features = ["full"] }
bytes = "1.5"
anyhow = "1.0"
thiserror = "1.0"
dashmap = "5.5"
log = "0.4"
env_logger = "0.10"